apache/roller

- app/src/main/java/org/apache/roller/weblogger/ui/struts2/core/Register.java
Related to no particular issue. This is a behavior-preserving refactoring.
Summary of this pull request:
•	We are evaluating a research prototype called Bandago that assists in the refactoring of complex methods. Bandago is an Eclipse plugin that automatically identifies and refactors a type of code smell called Brain Method. A Brain Method centralizes the intelligence of a class and manifests itself as a long and complex method that is difficult to understand and maintain We have applied Bandago to 2 complex methods of your project, and we would like to receive feedback.
•	Bandago is very conservative and you should not observe many source code changes (only in the affected class).
•	The source code (after the refactoring) should behave equivalently to the original one.
•	As a sanity …
> Refactoring complex methods of class Register

- app/src/main/java/org/apache/roller/weblogger/business/search/IndexManagerImpl.java
- app/src/main/java/org/apache/roller/weblogger/business/search/operations/IndexOperation.java
- app/src/main/resources/org/apache/roller/weblogger/config/roller.properties
https://issues.apache.org/jira/browse/ROL-2090
> Make some Lucene configuration adjustable

- app/src/main/java/org/apache/roller/weblogger/ui/core/security/RollerRememberMeAuthenticationProvider.java
- app/src/main/java/org/apache/roller/weblogger/ui/core/security/RollerRememberMeServices.java
- app/src/main/resources/org/apache/roller/weblogger/config/roller.properties
- app/src/main/webapp/WEB-INF/security.xml
if you're going to enable remember me then you must set a unqiue key; and not the well known "springRocks" that was the previous default.
https://issues.apache.org/jira/browse/ROL-2137
> [ROL-2137] Require setting rememberme.key

- app/pom.xml
- app/src/main/java/org/apache/roller/weblogger/business/search/FieldConstants.java
- app/src/main/java/org/apache/roller/weblogger/business/search/IndexManagerImpl.java
- app/src/main/java/org/apache/roller/weblogger/business/search/operations/IndexOperation.java
- app/src/main/java/org/apache/roller/weblogger/business/search/operations/ReadFromIndexOperation.java
- app/src/main/java/org/apache/roller/weblogger/business/search/operations/SearchOperation.java
Hello!
updated apache lucene from 4.x to 8.1.x which required some code changes. Since lucene can only read indexes which are not older than 1-2 major versions (according to the exception i got), I added a simple check which causes a rebuild task if the index is unreadable. (first commit)
The second commit removes usages of the deprecated RAMDirectory. I decided to not migrate it to MMapDirectory because the code path isn't used anywhere (or tested). Furthermore: MMapDirectory extends FSDirectory (which is currently used), so it wouldn't use the old code in any case.
tests are green and i also deployed a build to my blog and tested the index rebuilding once.
- - - - 
the only change i am not sure about is: https://github.com/mbien/roller/commit/10370c129dd5d5cb906095fc23be41bb69014179#diff …
> Apache Lucene Renovation

- Dockerfile
Fix for getting the war file from the right location.
Steps for validation:
```
git clone https://github.com/apache/roller.git
cd roller
docker build -t rollerdocker .
```
> War file location fix

- app/src/main/webapp/WEB-INF/jsps/admin/GlobalConfig.jsp
- pom.xml
1. Wrong tags in `site.frontpage.weblog.handle` select `listKey` and `listValueKey`, this will cause the database store wrong value;
2. For `#pd.type` is `boolean` used wrong `fieldValue` values, these tags will cause the `boolean` type value can not set to `true` values when you set any value before.
> Fix global config jsp page bugs

- app/src/main/webapp/WEB-INF/jsps/tiles/messages.jsp
1. Add close button
2. Remove bulleted text
3. Autoclose messages after 10 seconds
> Improve alert messages (ROL-2154)

- app/src/main/webapp/WEB-INF/jsps/editor/EntryEditor.jsp
Added custom code to add confimation box for text area which adds an event handler to beforeunload event if the text area is changed.
> Improved: Editor should confirm user before leaving the page (ROL-2136)

- app/pom.xml
NOTE:
Deprecated features are those that have been retained temporarily for backward compatibility, but which will eventually be removed. In effect, deprecation announces a grace period to allow the smooth transition from the old features to the new ones. In that period, no use of the deprecated features should be added, and all existing uses should be gradually removed.
> Improved: Replaced pom.basedir deprecated property with project.basedir. (ROL-2158)

- app/pom.xml
- pom.xml
- version-rules.xml
- use "no_aop" version of guice which doesn't bundle its own ASM version
- bumped ASM dependency to 7.2 for Java 13 compatibility
fixed some jetty warnings by not adding the javax.activation api classes twice.
minor maven dependency updates.
added version checker maven plugin, can be run with: mvn versions:display-dependency-updates.
> made it easier to run roller on latest JVMs (tested with JDK 13).

- app/src/main/webapp/WEB-INF/jsps/editor/MembersInvite.jsp
- app/src/main/webapp/WEB-INF/velocity/weblog.vm
- app/src/main/webapp/roller-ui/scripts/ajax-user.js
- app/src/main/webapp/theme/scripts/roller.js
- app/src/main/webapp/theme/scripts/searchhi.js
- app/src/main/webapp/themes/fauxcoly/searchhi.js
- app/src/main/webapp/themes/gaurav/js/searchhi.js
Pattern is identified and reported at  sonacloud.io as Blocker
JavaScript variable scope can be particularly difficult to understand and get right. The situation gets even worse when you consider the accidental creation of global variables, which is what happens when you declare a variable inside a function or the for clause of a for-loop without using the let, const or var keywords.
> Fixed: Variables should be declared explicitly in Custom JS code (ROL-2157)

- app/src/main/webapp/WEB-INF/jsps/admin/GlobalConfig.jsp
This PR works-around an apparent Struts but by showing weblog handle instead of name in front-page select. More details here: https://issues.apache.org/jira/browse/ROL-2160
> [ROL-2160] Fix for Server admin page failes to render bug

- app/src/main/resources/struts.xml
- app/src/main/webapp/WEB-INF/jsps/admin/UserEdit.jsp
- app/src/main/webapp/WEB-INF/jsps/core/CreateWeblog.jsp
- app/src/main/webapp/WEB-INF/jsps/core/Register.jsp
Create New user error - https://issues.apache.org/jira/browse/ROL-2161
This PR changes the User Registration and User Edit pages so that they allow email addresses up to 255 characters, which is the limit in the database. 
This PR also adds JavaScript form validation to the User Edit page to ensure that userName, fullName and email are valid.
> [ROL-2161] Create new user improvements

- app/pom.xml
- app/src/main/java/org/apache/roller/weblogger/business/search/IndexManagerImpl.java
- app/src/main/java/org/apache/roller/weblogger/util/cache/ExpiringLRUCacheImpl.java
- app/src/main/java/org/apache/roller/weblogger/util/cache/LRUCacheImpl.java
- pom.xml
I set this pull request against 6.0.x since master had bugs and was lacking behind last time I tried (see https://github.com/apache/roller/pull/58#issuecomment-616370669).
contents:
- better lucene search index compatibility. Point release updates won't trigger index rebuilds
- updated project dependencies to latest releases (skipped spring and webjars)
- removed double synchronization in cache
- tested on 11, 14 and 15b26
> search index compatibility and other minor changes

- app/pom.xml
- app/src/main/java/org/apache/roller/weblogger/pojos/User.java
- app/src/main/java/org/apache/roller/weblogger/ui/core/RollerContext.java
- app/src/main/java/org/apache/roller/weblogger/ui/core/filters/SpringFirewallExceptionFilter.java
- app/src/main/java/org/apache/roller/weblogger/ui/core/security/RollerRememberMeAuthenticationProvider.java
- app/src/main/java/org/apache/roller/weblogger/ui/core/security/RollerRememberMeServices.java
- app/src/main/java/org/apache/roller/weblogger/ui/struts2/admin/UserEdit.java
- app/src/main/java/org/apache/roller/weblogger/ui/struts2/core/Install.java
- app/src/main/java/org/apache/roller/weblogger/ui/struts2/core/Profile.java
- app/src/main/java/org/apache/roller/weblogger/webservices/atomprotocol/RollerAtomHandler.java
- app/src/main/java/org/apache/roller/weblogger/webservices/xmlrpc/BaseAPIHandler.java
- app/src/main/resources/org/apache/roller/weblogger/config/roller.properties
- app/src/main/webapp/WEB-INF/security.xml
- app/src/main/webapp/WEB-INF/web.xml
This PR contains the spring changes of the wip branch.
- spring upgrade to 5
- implementation of a DelegatingPasswordEncoder for lazy upgrades to modern pw encodings
details in the commit messages.
> Spring Renovations

- it-selenium/pom.xml
- it-selenium/src/test/java/org/apache/roller/selenium/AbstractRollerPage.java
- it-selenium/src/test/java/org/apache/roller/selenium/InitialLoginTestIT.java
- it-selenium/src/test/java/org/apache/roller/selenium/core/LoginPage.java
- it-selenium/src/test/java/org/apache/roller/selenium/core/MainMenuPage.java
- it-selenium/src/test/java/org/apache/roller/selenium/core/RegisterPage.java
- it-selenium/src/test/resources/roller-jettyrun.properties
integration tests should be working again.
commit msg:
- the pom was broken possibly from a merge conflict from some time ago
- fixed some paths and dependencies
- adapted for firefox driver api changes
- some tests needed minor updates due to the new bootstrap UI
- some tests threw StaleElementReference exceptions when they tried to access elements after
clicking a hyperlink which reloaded the page; fixed that too
tested with:
cd it-selenium
mvn clean integration-test -Dwebdriver.gecko.driver=/path/to/geckodriver
used:
geckodriver v0.26.0 on 64bit linux, latest firefox, jdk 14 and everything worked fine.
note:
do a mvn install of the roller root project first. Doing this for ./app is not sufficient
since the tests look for the project pom/war in local repo, not roller.war.
note2:
the …
> Fix for dusty integration tests

- app/pom.xml
- pom.xml
This change did not really improve the Jetty warnings about classes being loaded from two locations so I'm backing it out.
> back-out change to Spring dependency

- app/src/main/java/org/apache/roller/planet/business/jpa/JPAPlanetManagerImpl.java
Java 7 introduced the diamond operator (<>) to reduce the verbosity of generics code. For instance, instead of having to declare a List's type in both its declaration and its constructor, you can now simplify the constructor declaration with <>, and the compiler will infer the type.
Issue found using Sonar Cube.
> Fixed: type specification when using generics

- app/src/main/webapp/roller-ui/styles/menu.css
We have already defined `no-repeat` in the `background` css property so the `background-repeat` is duplicate so removed that property.
> Removed: unused css rule background-repeat from the menu.css file

- app/pom.xml
- app/src/main/java/org/apache/roller/weblogger/business/startup/DatabaseInstaller.java
- app/src/main/resources/sql/520-to-610-migration.vm
- app/src/main/resources/sql/dbscripts.properties
- app/src/main/resources/sql/macros.vm
- app/src/main/webapp/WEB-INF/jsps/tiles/head.jsp
- it-selenium/pom.xml
- pom.xml
The table name change requires an upgrade script. Its very generic SQL but don't know on how many DBs this is going to work. I only tested it with HSQLDB.
updated maven dependencies
- guice 5 can be used again without the noaop tag on latest jdks
- asm, spring, lucene, velocity etc
updated webjars
- bootstrap 3.4.1 is the last version before 4.x which comes with breaking changes
checked JDK16 compatibility
- required war plugin update in selenium pom
> Added Roller 6.1 db table upgrade logic + maven dependency upgrades

- app/src/test/java/org/apache/roller/weblogger/business/PlanetManagerLocalTest.java
PlanetManagerLocalTest leaves a subscription behind which causes SubscriptionFunctionalTest to fail if it is run after it.
This attempts to fix it by removing the subscription in the teardown.
> Fix for failing SubscriptionFunctionalTest

- app/src/main/webapp/WEB-INF/jsps/editor/Entries.jsp
Made the same UI for the published column and updated column in the blog entries table.
Also, reduced the width to 3% for the edit icon and delete icon column in the same table.
*Before:*
*After:*
> Improved: the UI for the blog entries page

- app/pom.xml
- app/src/main/java/org/apache/roller/util/ISO8601DateParser.java
- app/src/main/java/org/apache/roller/weblogger/business/jpa/JPAWeblogManagerImpl.java
- app/src/main/java/org/apache/roller/weblogger/ui/rendering/plugins/comments/MathCommentAuthenticator.java
- app/src/main/java/org/apache/roller/weblogger/ui/rendering/util/WeblogResourceRequest.java
- app/src/main/java/org/apache/roller/weblogger/ui/rendering/velocity/RollerVelocity.java
- app/src/main/java/org/apache/roller/weblogger/util/Utilities.java
- app/src/main/java/org/apache/roller/weblogger/util/cache/CachedContent.java
- app/src/main/java/org/apache/roller/weblogger/webservices/atomprotocol/RollerAtomHandler.java
- app/src/main/java/org/apache/roller/weblogger/webservices/xmlrpc/MetaWeblogAPIHandler.java
Noticed that the cache copies its contents twice since flush() + close() are used in sequence in the entire codebase. CachedContent.close() will now only update the content if something changed.
+ added some other minor performance related commits
+ fixed one leaking input stream
+ point release dependency updates
> Small performance improvements

- app/pom.xml
- app/src/main/java/org/apache/roller/weblogger/util/IPBanList.java
- app/src/test/java/org/apache/roller/weblogger/util/IPBanListTest.java
Fixes some concurrency issues in the IPBanList class:
* It calls HashSet#contains() from outside a synchronized block: it might not be able to catch a change made by a different thread
* The bannedIps field is not volatile even though multiple threads can set it to a new instance from loadBannedIps(): other threads might not see the updated instance
There are also some minor code improvements suggested by IntelliJ
> Ipbanlist fixes

- app/src/main/resources/ApplicationResources.properties
1. Improved the tooltip content for the screen name in the registration form
> Improved: tooltip content on the registration form

- app/pom.xml
- it-selenium/pom.xml
- pom.xml
- class path is now properly set up for the selenium tests (no jetty warnings anymore, significantly faster startup)
- some maven cleanup to remove duplicate libraries in classpath
- removed unused dependencies (e.g xml-security)
- updated maven dependencies 
- added -Xlint:deprecation as compiler arg for future cleanups
no code changes
note: spring security was not updated to 5.5.0 since https://github.com/spring-projects/spring-security/issues/9811 would have pulled in kotlin libraries
> Improved selenium test classpath + maven updates.

- app/pom.xml
This PR removes provided scope for JSTL becuase JSTL is not provided by Tomcat. I erroneously added provided scope a couple months ago when I was trying to get the Maven Jetty stuff working.
> Remove provided scope for JSTL

- app/src/main/java/org/apache/roller/weblogger/business/jpa/JPAWeblogManagerImpl.java
- app/src/main/java/org/apache/roller/weblogger/ui/rendering/plugins/comments/CommentAuthenticatorUtils.java
- app/src/main/java/org/apache/roller/weblogger/ui/rendering/servlets/CommentServlet.java
- app/src/main/java/org/apache/roller/weblogger/ui/rendering/servlets/FeedServlet.java
- app/src/main/java/org/apache/roller/weblogger/ui/rendering/servlets/SearchServlet.java
- app/src/main/java/org/apache/roller/weblogger/ui/rendering/util/WeblogFeedRequest.java
- app/src/main/java/org/apache/roller/weblogger/ui/rendering/util/WeblogRequest.java
- app/src/main/java/org/apache/roller/weblogger/ui/rendering/velocity/RollerResourceLoader.java
- app/src/main/java/org/apache/roller/weblogger/ui/rendering/velocity/VelocityRenderer.java
- app/src/main/java/org/apache/roller/weblogger/ui/rendering/velocity/VelocityRendererFactory.java
- app/src/main/java/org/apache/roller/weblogger/ui/struts2/editor/EntryBean.java
- app/src/main/java/org/apache/roller/weblogger/webservices/opensearch/OpenSearchServlet.java
- app/src/main/java/org/apache/roller/weblogger/webservices/tagdata/TagDataServlet.java
- app/src/main/webapp/WEB-INF/web.xml
Add early input validation for weblog handles and similar parameters so that roller can respond early instead of responding later in the business logic. 
Output encode client provided strings.
Improved Exception handling / Error page mapping.
> Improve input validation

- app/src/main/java/org/apache/roller/weblogger/pojos/WeblogEntryComment.java
- app/src/main/webapp/WEB-INF/jsps/editor/Comments.jsp
second attempt of https://github.com/apache/roller/pull/64
removed getEmptyString() since listValue="" has the same effect and makes WildFly happy too.
> fix for PropertyNotFoundException when started in WildFly

- app/src/main/webapp/WEB-INF/jsps/core/MainMenu.jsp
Added space between the permission message.
Before:
After:
> Updated: the main menu to have proper space when displaying permission message

- app/src/main/webapp/themes/fauxcoly/std_header.vm
- app/src/main/webapp/themes/gaurav/weblog.vm
Added an if condition to check whether the weblog has a tagline defined or not and if there is a tagline present then only displaying the tagline.
Before:
Tagline is always displayed.
After:
Tagline is only displayed when its defined
If tagline is not present then nothing is displayed.
> Updated: the header to show the tagline only when its available

- .github/workflows/codeql-analysis.yml
- app/src/main/java/org/apache/roller/planet/tasks/GeneratePlanetTask.java
- app/src/main/java/org/apache/roller/weblogger/ui/rendering/mobile/MobileDeviceRepository.java
- app/src/main/java/org/apache/roller/weblogger/ui/rendering/velocity/RollerVelocity.java
- app/src/main/java/org/apache/roller/weblogger/ui/rendering/velocity/WebappResourceLoader.java
- app/src/main/resources/log4j2.xml
- app/src/main/webapp/WEB-INF/jsps/tiles/search.jsp
- app/src/main/webapp/WEB-INF/velocity.properties
- app/src/main/webapp/WEB-INF/web.xml
- app/src/test/resources/WEB-INF/velocity.properties
fixes usage of deprecated velocity properties. I extracted the warnings out of JFR logs and did a project wide search and replace. Log level for velocity can be set to info again I suppose.
The other commits fix an encoding issue and add a smaller security improvement for session cookies.
here the extracted list:
```
deprecation: configuration key 'class.resource.loader.cache' has been deprecated in favor of 'resource.loader.class.cache' 
deprecation: configuration key 'class.resource.loader.class' has been deprecated in favor of 'resource.loader.class.class' 
deprecation: configuration key 'class.resource.loader.description' has been deprecated in favor of 'resource.loader.class.description' 
deprecation: configuration key 'class.resource.loader.modificationCheckInterval' has been …
```
> Velocity property warning fixes

- .github/codeql/codeql-config.yml
- .github/workflows/codeql-analysis.yml
- app/src/main/java/org/apache/roller/weblogger/business/FileContentManagerImpl.java
- app/src/main/java/org/apache/roller/weblogger/business/themes/ThemeManagerImpl.java
- app/src/main/java/org/apache/roller/weblogger/ui/core/filters/InitFilter.java
- app/src/main/java/org/apache/roller/weblogger/ui/core/security/RollerRememberMeServices.java
- app/src/main/java/org/apache/roller/weblogger/ui/rendering/WeblogRequestMapper.java
- app/src/main/java/org/apache/roller/weblogger/ui/struts2/editor/FolderEdit.java
- app/src/main/java/org/apache/roller/weblogger/webservices/tagdata/TagDataServlet.java
- app/src/main/webapp/theme/scripts/roller.js
This PR closes some (~14) CodeQL alerts.
Most of them could be fixed by restructuring the code a little.
75ba795 changes the config so that JS alerts don't show up three times.
I am thinking about closing two additional alerts manually:
- [URL redirection from remote source](https://github.com/apache/roller/security/code-scanning/21?query=ref%3Arefs%2Fheads%2Fmaster) Since weblogHandle is validated [here](https://github.com/mbien/roller/blob/9e017c5535b51853b20502fe73fc821e88c681ab/app/src/main/java/org/apache/roller/weblogger/ui/rendering/WeblogRequestMapper.java#L133-L136) and used [here](https://github.com/mbien/roller/commit/b443ee4f4510f67781aab35e3c6dbefefc605060). As false positive
- [Server-side request forgery](https://github.com/apache/roller/security/code-scanning/67?query=ref%3 …
> CodeQL fixes

- app/src/main/java/org/apache/roller/weblogger/ui/rendering/util/cache/SiteWideCache.java
- app/src/main/java/org/apache/roller/weblogger/ui/rendering/util/cache/WeblogPageCache.java
Small fix. Did not impact functionality, just the way cache keys were generated.
bug introduced in  7d07a84
> "/tags/" appears twice in the cache key.

- app/src/main/webapp/WEB-INF/jsps/editor/MediaFileView.jsp
As noticed by Greg Huber on the mailing list, deleting a folder in the media file view results in a JS error. (although the folder is still deleted)
this fixes it.
> MediaFileView.jsp delete folder JS error fix

- app/pom.xml
- app/src/main/webapp/WEB-INF/jsps/tiles/head.jsp
- pom.xml
highlights:
- log4j 2.15.0 (fixes security vulnerability[1][2][3])
- lucene 9 (artifact name changed)
- spring security 5.6
- jquery-ui 1.13 via webjar
- other minor version bumps
[1] https://www.lunasec.io/docs/blog/log4j-zero-day/
[2] https://github.com/apache/logging-log4j2/pull/608
[3] https://github.com/advisories/GHSA-jfh8-c2jp-5v3q
> maven dependency updates

- app/pom.xml
another log4j2 version bump
- disables JNDI by default
- removes support for msg lookups
https://logging.apache.org/log4j/2.x/changes-report.html#a2.16.0
> Dependency update to log4j2 2.16.

- Dockerfile
- docker/entry-point.sh
- fixed urls
- upgraded to jdk17 and latest lib versions
- better signal handling (made sure container stop signal propagates to tomcat)
i leave this as draft until we have a tag for 6.1, so i can change the git checkout line.
> updated container setup.

- .github/workflows/codeql-analysis.yml
- .github/workflows/main.yml
- app/src/test/java/org/apache/roller/weblogger/util/IPBanListTest.java
- it-selenium/src/test/java/org/apache/roller/selenium/InitialLoginTestIT.java
- builds/tests on JDK 11 and 17
- uploads junit report
- disabled a failing test for now
> Added github actions for basic build/test setup.

- app/pom.xml
- app/src/main/java/org/apache/roller/weblogger/business/startup/DatabaseInstaller.java
- app/src/main/java/org/apache/roller/weblogger/ui/core/RollerContext.java
- **notable dependency update: spring 5.3.18** with **security** fixes for "[spring4shell](https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORK-2436751)"
- bouncy castle was added so that the popular Argon2 pw encoder can be used
available (non legacy) encoders: bcrypt, pbkdf2, scrypt, argon2
**Reminder how to change the encoder:**
`passwds.encryption.algorithm=argon2`, default remains `pbkdf2`
automatic migration happens on next pw change
**If one of the (very, very) old legacy codecs is still in use, roller will need a hint for migration**
`passwds.encryption.lazyUpgradeFrom=`
possible options: `plaintext, MD5, SHA-1` can be left empty if the db doesn't contain any legacy encoded pws
@snoopdave might be a good time for another point release :)
> dependency updates, added bouncycastle, minor log level update.

- .github/workflows/main.yml
upload a dev build as CI step.
> upload dev build + add JDK 18 to the matrix + version bumps.

- app/pom.xml
- app/src/main/java/org/apache/roller/planet/business/jpa/JPAPlanetManagerImpl.java
- app/src/main/java/org/apache/roller/weblogger/business/jpa/JPAAutoPingManagerImpl.java
- app/src/main/java/org/apache/roller/weblogger/business/jpa/JPABookmarkManagerImpl.java
- app/src/main/java/org/apache/roller/weblogger/business/jpa/JPAMediaFileManagerImpl.java
- app/src/main/java/org/apache/roller/weblogger/business/jpa/JPAOAuthManagerImpl.java
- app/src/main/java/org/apache/roller/weblogger/business/jpa/JPAPersistenceStrategy.java
- app/src/main/java/org/apache/roller/weblogger/business/jpa/JPAPingQueueManagerImpl.java
- app/src/main/java/org/apache/roller/weblogger/business/jpa/JPAPingTargetManagerImpl.java
- app/src/main/java/org/apache/roller/weblogger/business/jpa/JPAThreadManagerImpl.java
- app/src/main/java/org/apache/roller/weblogger/business/jpa/JPAUserManagerImpl.java
- app/src/main/java/org/apache/roller/weblogger/business/jpa/JPAWeblogEntryManagerImpl.java
- app/src/main/java/org/apache/roller/weblogger/business/jpa/JPAWeblogManagerImpl.java
- app/src/main/webapp/WEB-INF/jsps/tiles/head.jsp
- jakarta namespace update allows roller to use eclipse link 3.x.
- minor dependency updates (asm, lucene, spring, jquery-ui webjar)
struts wasn't updated due to some breaking changes, see:
- https://github.com/apache/struts/pull/496
- https://cwiki.apache.org/confluence/display/WW/Version+Notes+2.5.30
> Upgrade to Jakarta Eclipselink + other minor dependency bumps

- README.md
- app/pom.xml
- app/src/main/java/org/apache/roller/weblogger/business/startup/SQLScriptRunner.java
- app/src/main/resources/sql/droptables.sql
- app/src/test/java/org/apache/roller/util/DerbyManager.java
- app/src/test/java/org/apache/roller/weblogger/TestUtils.java
- app/src/test/resources/roller-custom.properties
- assembly-release/pom.xml
- assembly-release/sign-release.sh
- it-selenium/pom.xml
- pom.xml
This PR removes the Maven Plugin that was used to start/stop Derby and re-introduces some old code that starts Derby via Java and creates the Roller schema before tests run and stops Derby after they complete.
Also, changes version to `6.1.2-SNAPSHOT`
> Start Derby from Java so tests can run without Maven

- .github/workflows/codeql-analysis.yml
- .github/workflows/main.yml
- app/pom.xml
- app/src/main/webapp/WEB-INF/jsps/tiles/head.jsp
- app/src/test/java/org/apache/roller/weblogger/business/CommentTest.java
- app/src/test/java/org/apache/roller/weblogger/business/MediaFileTest.java
- pom.xml
- the test-summary action has [been allowed by infra](https://issues.apache.org/jira/browse/INFRA-23445) for CI use and works fairly well for the NetBeans project where we use it since then. The only annoyance is that it ignores errors, while it will pick up junit failures, but a PR is pending for that.
It writes test reports directly to the workflow summary page (not to checks, which felt like a workaround anyway).
- test runners should have geckodriver preinstalled, lets see if we can simply set a path to it.
- enabled xserver for headful integration testing
- minor maven dependency updates
- gh action version updates since they cause warnings
- bump JDK 18 to ~19~ 20 in the test matrix
tested locally.. lets see if everything builds with CI too
> minor dependency updates + test-summary workflow action

- .github/workflows/main.yml
- app/pom.xml
- app/src/main/webapp/WEB-INF/jsps/tiles/head.jsp
- pom.xml
Mostly minor dependency updates which should allow roller to run on the upcoming JDK 21.
The only major update was guice, guice 6.x and 7.x are nearly identical taken from doc:
> The Guice 6.0 servlet & persist extensions only support the javax.servlet and javax.persistence namespaces respectively. If compatibility with jakarta.servlet or jakarta.persistence is required, use Guice 7.0.
> 
> Guice 7.0 removes support for javax.inject, javax.servlet and javax.persistence. Other than the namespace changes, Guice 6.0 & Guice 7.0 are identical.
updated from 5.x to 6.0 for now.
> Dependency updates (JDK 21 compatibility)

- app/src/main/java/org/apache/roller/weblogger/pojos/Weblog.java
- app/src/main/java/org/apache/roller/weblogger/pojos/WeblogCategory.java
- app/src/main/java/org/apache/roller/weblogger/ui/struts2/editor/WeblogConfigBean.java
- app/src/main/java/org/apache/roller/weblogger/util/HTMLSanitizer.java
- docs/roller-install-guide.adoc
- docs/roller-user-guide.adoc
This PR sanitizes a couple of inputs and adds some docs clarifications.
> Santize some inputs and clarify docs

- app/pom.xml
- app/src/main/java/org/apache/roller/weblogger/business/startup/WebloggerStartup.java
- app/src/main/java/org/apache/roller/weblogger/ui/core/RollerContext.java
- app/src/test/java/org/apache/roller/weblogger/TestUtils.java
- app/src/test/resources/jetty.xml
- app/src/test/resources/roller-jettyrun.properties
- db-utils/pom.xml
- db-utils/src/main/java/org/apache/roller/testutils/DerbyLifeCycle.java
- it-selenium/pom.xml
- it-selenium/src/test/resources/roller-jettyrun.properties
- pom.xml
This PR fixes a regression caused by switching Roller from using the Maven `btmatthews` `inmemdb` plugin and instead starting Derby by calling the embedded Derby server API directly (which works when tests are run either in IntelliJ or in Maven).  The problem was that I forgot to add the same logic to the Maven Jetty plugin so that Derby is started when Roller is run via `mvn jetty:run`.
The Jira ticket: https://issues.apache.org/jira/browse/ROL-2182
> Add a Jetty event listener to start Derby when Roller is run via mvn jetty:run

- .github/workflows/codeql-analysis.yml
- .github/workflows/main.yml
- app/pom.xml
- app/src/main/webapp/WEB-INF/jsps/tiles/head.jsp
- app/src/test/java/org/apache/roller/planet/business/GroupFunctionalTests.java
- app/src/test/java/org/apache/roller/planet/business/PlanetFunctionalTests.java
- app/src/test/java/org/apache/roller/weblogger/business/BookmarkTest.java
- app/src/test/java/org/apache/roller/weblogger/business/CommentTest.java
- app/src/test/java/org/apache/roller/weblogger/business/FolderFunctionalityTest.java
- app/src/test/java/org/apache/roller/weblogger/business/HitCountTest.java
- app/src/test/java/org/apache/roller/weblogger/business/MediaFileTest.java
- app/src/test/java/org/apache/roller/weblogger/business/PermissionTest.java
- app/src/test/java/org/apache/roller/weblogger/business/PingsTest.java
- app/src/test/java/org/apache/roller/weblogger/business/PlanetManagerLocalTest.java
- app/src/test/java/org/apache/roller/weblogger/business/UserTest.java
- app/src/test/java/org/apache/roller/weblogger/business/WeblogCategoryFunctionalityTest.java
- app/src/test/java/org/apache/roller/weblogger/business/WeblogEntryTest.java
- app/src/test/java/org/apache/roller/weblogger/business/WeblogPageTest.java
- app/src/test/java/org/apache/roller/weblogger/business/WeblogStatsTest.java
- app/src/test/java/org/apache/roller/weblogger/business/WeblogTest.java
- app/src/test/java/org/apache/roller/weblogger/ui/ApplicationResourcesTest.java
- db-utils/pom.xml
- it-selenium/nbactions.xml
- it-selenium/pom.xml
- it-selenium/src/test/java/org/apache/roller/selenium/AbstractRollerPage.java
- it-selenium/src/test/java/org/apache/roller/selenium/core/RegisterPage.java
- pom.xml
- update project dependencies
- selenium tests don't need an external geckodriver anymore
- update setup-java, checkout and upload-artifact github actions
- fixed rawtype compiler warnings in tests
> Dependency updates and some compiler warning cleanup in tests

- app/pom.xml
- app/src/main/webapp/WEB-INF/jsps/tiles/head.jsp
- it-selenium/pom.xml
- pom.xml
- asm, spring, lucene, logging, apache commons libs
- webjars: jquery and jquery-validation
- build: junit, selenium and other maven plugins
note: spring closed [CVE-2024-38816](https://www.herodevs.com/vulnerability-directory/cve-2024-38816), but it shouldn't affect roller since we don't use `spring-webmvc` or `spring-webflux`
> dependency updates

- app/src/main/java/org/apache/roller/weblogger/pojos/wrapper/WeblogWrapper.java
- app/src/main/java/org/apache/roller/weblogger/ui/core/filters/LoadSaltFilter.java
- app/src/main/java/org/apache/roller/weblogger/ui/core/filters/ValidateSaltFilter.java
- app/src/main/java/org/apache/roller/weblogger/ui/struts2/editor/WeblogConfig.java
- app/src/main/resources/ApplicationResources.properties
- app/src/main/webapp/WEB-INF/jsps/editor/WeblogConfig.jsp
- app/src/test/java/org/apache/roller/weblogger/ui/core/filters/LoadSaltFilterTest.java
- app/src/test/java/org/apache/roller/weblogger/ui/core/filters/ValidateSaltFilterTest.java
This PR implements one-time use salts, improves URL matching for ignored URLs, and enhances security in ValidateSaltFilter and LoadSaltFilter. It also adds comprehensive unit tests for both filters to ensure proper functionality and edge case handling. The changes include:
* Implementing one-time use salts by removing them from the cache after validation
* Improving URL matching to consider full URLs including query parameters
* Enhancing security checks in ValidateSaltFilter
* Adding robust unit tests for both filters
* Refactoring code for better readability and maintainability
> Implement one-time-salt use and add comprehensive tests
